# Generated by Django 2.0 on 2020-07-16 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='REG',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('manager', models.CharField(max_length=10)),
                ('coach', models.CharField(max_length=10)),
                ('player1', models.CharField(max_length=10)),
                ('player2', models.CharField(max_length=10)),
                ('player3', models.CharField(max_length=10)),
                ('player4', models.CharField(max_length=10)),
                ('player5', models.CharField(max_length=10)),
                ('player6', models.CharField(max_length=10)),
                ('player7', models.CharField(max_length=10)),
                ('player8', models.CharField(max_length=10)),
                ('player9', models.CharField(max_length=10)),
                ('player10', models.CharField(max_length=10)),
                ('player11', models.CharField(max_length=10)),
                ('player12', models.CharField(max_length=10)),
                ('sub1', models.CharField(max_length=10)),
                ('sub2', models.CharField(max_length=10)),
                ('sub3', models.CharField(max_length=10)),
            ],
        ),
    ]
