# Generated by Django 2.0 on 2020-07-16 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reg',
            name='coach',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='manager',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player10',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player11',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player12',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player3',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player4',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player5',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player6',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player7',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player8',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='player9',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='sub1',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='sub2',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='reg',
            name='sub3',
            field=models.CharField(max_length=20),
        ),
    ]
