# Generated by Django 2.0 on 2020-07-16 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0002_auto_20200716_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reg',
            name='player12',
        ),
    ]
