# Generated by Django 2.0 on 2020-07-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0003_remove_reg_player12'),
    ]

    operations = [
        migrations.CreateModel(
            name='fixture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('venue', models.CharField(max_length=20)),
            ],
        ),
    ]
