# Generated by Django 2.0 on 2020-07-16 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('footballapp', '0004_fixture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fixture',
            name='team',
        ),
        migrations.AddField(
            model_name='fixture',
            name='team1',
            field=models.CharField(default='a', max_length=30),
        ),
        migrations.AddField(
            model_name='fixture',
            name='team2',
            field=models.CharField(default='b', max_length=30),
        ),
        migrations.AlterField(
            model_name='fixture',
            name='venue',
            field=models.CharField(default='c', max_length=20),
        ),
    ]
